// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const createSSRApp: typeof import('vue')['createSSRApp']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const reactive: typeof import('vue')['reactive']
  const ref: typeof import('vue')['ref']
  const useElementVisibility: typeof import('@vueuse/core')['useElementVisibility']
  const useSSRContext: typeof import('vue')['useSSRContext']
}
export {}
